[tool.poetry]
name = "mlrq"
version = "0.1.0"
description = ""
authors = ["Filippos Christianos <f.christianos@ed.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
redis = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
